version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run: gradle clean

      - run: gradle assemble

      - run:
          name: gradle test
          command: |
            ./cc-test-reporter before-build
            gradle test
            ./cc-test-reporter after-build --exit-code $EXIT_CODE?

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/kyu1/ ~/junit/kyu2/ ~/junit/kyu3/ ~/junit/kyu4/ ~/junit/kyu5/ ~/junit/kyu6/ ~/junit/kyu7/ ~/junit/kyu8/
            find . -type f -regex ".*/build/test-results/.*kyu1.*xml" -exec cp {} ~/junit/kyu1/ \;
            find . -type f -regex ".*/build/test-results/.*kyu2.*xml" -exec cp {} ~/junit/kyu2/ \;
            find . -type f -regex ".*/build/test-results/.*kyu3.*xml" -exec cp {} ~/junit/kyu3/ \;
            find . -type f -regex ".*/build/test-results/.*kyu4.*xml" -exec cp {} ~/junit/kyu4/ \;
            find . -type f -regex ".*/build/test-results/.*kyu5.*xml" -exec cp {} ~/junit/kyu5/ \;
            find . -type f -regex ".*/build/test-results/.*kyu6.*xml" -exec cp {} ~/junit/kyu6/ \;
            find . -type f -regex ".*/build/test-results/.*kyu7.*xml" -exec cp {} ~/junit/kyu7/ \;
            find . -type f -regex ".*/build/test-results/.*kyu8.*xml" -exec cp {} ~/junit/kyu8/ \;
            find . -type f -regex ".*/build/test-results/.*^kyu[1-8].*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit
